### PR TITLE
Feature/holdings fortune modifier

### PR DESCRIPTION
**Pull request by YolloDwarf**
Moved PR #52 to develop branch

### CODE REVIEW

**Comment by 3darkman** [comment]
thanks for pointing to develop.... 

continuing the conversation, I completely agree with you, the Foundry documentation is horrible, it doesn't have examples, or details about how things work. You have to learn everything by looking at code from other systems. 

I understand that I made a lot of bad decisions on this system while I was learning, so try to ignore any oddities in the code that you can see. 

I'm leaving home today, and I won't be back until Monday, although I can still follow it here on github on my cell phone, I won't be able to test things, so I'll check everything next week (mainly because today is my last day of work before my vacation)

**Comment by YolloDwarf** [comment]
I get that Foundry is pretty indie but for something that's supposed to be powered up by user generated content, I feel that they should focus on building up the docs way more before launching into developing new features. I understand it's a pain in the butt and being in constant development, stuff might just get thrown out of the window and rebuilt but having a more readable doc would ensure a bigger developing community, leading to less responsibility on the Foundry devs to add every new feature...

My Foundry API knowledge is pretty non-existent so I wen in tackling something that looked easy and it seems to be working! With combat automation it's gonna be way harder and I'm taking some time to learn how hooks and templating works since I wanted to make custom cards to promp the calculation (seemed easier to apply damage from a chat button rather than on roll).

I'll be pretty busy in the holidays too, so have a nice Christmas and a good New Year!

**Comment by 3darkman** [comment]
ahhh, I think it must have some remnants of an attempt to make cards to calculate the margins of success. I don't remember if it's on the develop branch, or if I created a specific branch for that, I didn't continue because I ran out of time and people were asking for other priorities. 

have a nice Christmas too! :)

**Comment by TitanicViking** [comment]
Margins of Success would be fantastic honestly. :D

**Comment by 3darkman** [comment]
@YolloDwarf hey man, happy new year. 

i'm testing your PR, and I missed the holding modifier field on the holding sheet, did you forget tosend this?

**Comment by YolloDwarf** [comment]
Happy new year!

I'm gonna check right now why stuff didn't get added!

**Comment by YolloDwarf** [comment]
After looking at commit history, it seems like some stuff got messed up and deleted. I'll let you know as soon as I manage to restore everything to a functioning status!

**Comment by YolloDwarf** [comment]
I think I managed to have it work again. I re-zipped the system folders, unpacked in the foundry directory and everything works. Hopefully this is it

image

**Comment by 3darkman** [comment]
there is still an error in the pull request, the end of the formgroup is incomplete as shown in the attached image, and it also seems that there was a problem with a line break in the en.json file.

So we don't waste any more time, I'm going to make this change manually, but try to stay tuned if you're going to make new PR. Oh and please, do not change the .zip of the folder, because I only change it at the end when I package everything.

image

**Pull request closed without merging**
